[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
path = "/api/health"
interval = "60s"
timeout = "30s"
retries = 5
grace_period = "60s"

[variables]
PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING = "1" 