[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
path = "/api/health"
interval = "30s"
timeout = "10s"
retries = 3
grace_period = "30s"

[variables]
PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING = "1" 